orchestra/accounts/urls.py
from django.urls import re_path
from django.views.generic import RedirectView

from orchestra.accounts.views import AccountSettingsView
from orchestra.accounts.views import AvailabilitySettingsView
from orchestra.accounts.views import CommunicationPreferenceSettingsView
from orchestra.accounts.views import OrchestraRegistrationView

urlpatterns = [
    # We have to override the register endpoint to emit the
    # `orchestra_user_registered` signal
    re_path(r'^accounts/register/$',
            OrchestraRegistrationView.as_view(),
            name='registration_register'),
    re_path(r'^accounts/settings/$',
            AccountSettingsView.as_view(), name='account_settings'),
    re_path(r'^accounts/communication_preference_settings/$',
            CommunicationPreferenceSettingsView.as_view(),
            name='communication_preference_settings'),
    re_path(r'^accounts/availability_settings/$',
            AvailabilitySettingsView.as_view(),
            name='availability_settings'),
    re_path(r'^password/change/done/$',
            RedirectView.as_view(
                pattern_name='account_settings'),
            name='auth_password_change_done'),
]

orchestra/urls.py
from django.conf.urls import include
from django.urls import re_path

from orchestra.views import index
from orchestra.views import newindex
from orchestra.views import status

app_name = 'orchestra'

urlpatterns = [
    re_path(r'^api/',
            include('orchestra.api_urls', namespace='orchestra')),
    re_path(r'^communication/',
            include('orchestra.communication.urls',
                    namespace='communication')),
    re_path(r'^newapp/?', newindex, name='newindex'),
    re_path(r'^app/?', index, name='index'),
    re_path(r'', include('orchestra.accounts.urls')),
    re_path(r'^bots/', include('orchestra.bots.urls', namespace='bots')),
    re_path(r'^todos/', include('orchestra.todos.urls', namespace='todos')),

    # Health check status
    re_path(r'^status/', status, name='status'),
]

orchestra/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from phonenumber_field.formfields import SplitPhoneNumberField

from orchestra.accounts.bitformfield import BitFormField
from orchestra.communication.slack import get_slack_user_id
from orchestra.models import CommunicationPreference
from orchestra.models import Worker
from orchestra.models import WorkerAvailability


UserModel = get_user_model()


class UserForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()

    class Meta:
        model = UserModel
        fields = ('first_name', 'last_name')
        # TODO(joshblum): support change email
        exclude = ('is_staff', 'is_active', 'date_joined', 'username', 'email')


class DailyAvailabilityField(forms.FloatField):
    def __init__(self, *args, **kwargs):
        max_value = 24  # only 24 hours in a day!
        super().__init__(*args, min_value=0, max_value=max_value, **kwargs)


class WorkerAvailabilityForm(forms.ModelForm):
    class Meta:
        model = WorkerAvailability
        fields = (
            'hours_available_mon',
            'hours_available_tues',
            'hours_available_wed',
            'hours_available_thurs',
            'hours_available_fri',
            'hours_available_sat',
            'hours_available_sun',
        )
        field_classes = {field: DailyAvailabilityField for field in fields}


class WorkerForm(forms.ModelForm):
    slack_username = forms.CharField()
    phone = SplitPhoneNumberField(region='US')

    class Meta:
        model = Worker
        fields = ('slack_username', 'phone')
        exclude = ('user', 'start_datetime', 'slack_user_id')

    def clean_slack_username(self):
        slack_username = self.cleaned_data.get('slack_username')
        if slack_username:
            slack_user_id = get_slack_user_id(slack_username)
            if slack_user_id is None:
                raise forms.ValidationError(
                    'Incorrect slack username provided')
            self.cleaned_data['slack_user_id'] = slack_user_id
        return self.cleaned_data['slack_username']

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.slack_user_id = self.cleaned_data.get('slack_user_id')
        if commit:
            instance.save()
        return instance


class CommunicationPreferenceForm(forms.ModelForm):
    methods = BitFormField()

    class Meta:
        model = CommunicationPreference
        fields = ('methods',)
        exclude = ('worker', 'is_deleted',
                   'created_at')

orchestra/accounts/views.py
from datetime import timedelta

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.forms import modelformset_factory
from django.http import Http404
from django.shortcuts import render
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import View
from registration.models import RegistrationProfile
from registration.views import RegistrationView

from orchestra.accounts import signals
from orchestra.accounts.bitformfield import BitFormField
from orchestra.accounts.forms import CommunicationPreferenceForm
from orchestra.accounts.forms import UserForm
from orchestra.accounts.forms import WorkerAvailabilityForm
from orchestra.accounts.forms import WorkerForm
from orchestra.models import CommunicationPreference
from orchestra.models import Worker
from orchestra.models import WorkerAvailability
from orchestra.utils.datetime_utils import first_day_of_the_week


UserModel = get_user_model()


class OrchestraRegistrationView(RegistrationView):
    SEND_ACTIVATION_EMAIL = getattr(settings, 'SEND_ACTIVATION_EMAIL', True)
    success_url = 'registration_complete'

    def register(self, form):
        """
        Given a username, email address and password, register a new
        user account, which will initially be inactive.
        Along with the new ``User`` object, a new
        ``registration.models.RegistrationProfile`` will be created,
        tied to that ``User``, containing the activation key which
        will be used for this account.
        An email will be sent to the supplied email address; this
        email should contain an activation link. The email will be
        rendered using two templates. See the documentation for
        ``RegistrationProfile.send_activation_email()`` for
        information about these templates and the contexts provided to
        them.
        After the ``User`` and ``RegistrationProfile`` are created and
        the activation email is sent, the signal
        ``orchestra.signals.orchestra_user_registered`` will be sent,
        with the new ``User`` as the keyword argument ``user`` and the
        class of this backend as the sender.
        """
        site = get_current_site(self.request)

        if hasattr(form, 'save'):
            new_user_instance = form.save()
        else:
            new_user_instance = (UserModel().objects
                                 .create_user(**form.cleaned_data))

        new_user = RegistrationProfile.objects.create_inactive_user(
            new_user=new_user_instance,
            site=site,
            send_email=self.SEND_ACTIVATION_EMAIL,
            request=self.request,
        )

        # We send our own custom signal here so we don't conflict with anyone
        # using the django-registration project
        signals.orchestra_user_registered.send(sender=self.__class__,
                                               user=new_user,
                                               request=self.request)
        return new_user


@method_decorator(login_required, name='dispatch')
class WorkerViewMixin(View):

    def dispatch(self, request, *args, **kwargs):
        self.set_context_data(request, *args, **kwargs)
        return super().dispatch(request, *args, **kwargs)

    def set_context_data(self, request, *args, **kwargs):
        self.worker = Worker.objects.get(user=request.user)


class AccountSettingsView(WorkerViewMixin):
    template_name = 'accounts/settings.html'
    user_form = UserForm
    worker_form = WorkerForm

    def get(self, request, *args, **kwargs):
        user_form = self.user_form(
            instance=request.user)
        worker_form = self.worker_form(instance=self.worker)

        return render(request, self.template_name, {
            'user_form': user_form,
            'worker_form': worker_form,
            'worker': self.worker,
        })

    def post(self, request, *args, **kwargs):
        user_form = self.user_form(
            data=request.POST, instance=request.user)
        worker_form = self.worker_form(
            data=request.POST, instance=self.worker)

        success = user_form.is_valid() and worker_form.is_valid()
        if success:
            user_form.save()
            worker_form.save()

        return render(request, self.template_name, {
            'user_form': user_form,
            'worker_form': worker_form,
            'worker': self.worker,
            'success': success,
        })


class CommunicationPreferenceSettingsView(WorkerViewMixin):
    template_name = 'accounts/communication_preferences_settings.html'
    comm_pref_form = CommunicationPreferenceForm
    default_choices = CommunicationPreference.COMMUNICATION_METHODS
    method_choices = {
        CommunicationPreference.CommunicationType.TASK_STATUS_CHANGE.value:
        ((CommunicationPreference.CommunicationMethods.EMAIL, 'Email'),),
    }

    def set_context_data(self, request, *args, **kwargs):
        super().set_context_data(request, *args, **kwargs)
        self.comm_prefs = CommunicationPreference.objects.filter(
            worker=self.worker)
        self.CommunicationPreferenceFormSet = modelformset_factory(
            CommunicationPreference,
            form=CommunicationPreferenceForm,
            extra=0
        )
        self.descriptions = [comm_pref.get_descriptions()
                             for comm_pref in self.comm_prefs]

    def set_method_choices(self, formset):
        for form in formset:
            comm_type = form.instance.communication_type
            choices = self.method_choices.get(comm_type,
                                              self.default_choices)
            form.fields['methods'] = BitFormField(choices=self.default_choices,
                                                  widget_choices=choices)

    def get(self, request, *args, **kwargs):
        comm_pref_formset = self.CommunicationPreferenceFormSet(
            queryset=self.comm_prefs)
        self.set_method_choices(comm_pref_formset)
        return render(request, self.template_name, {
            'form_data': zip(comm_pref_formset, self.descriptions),
            'comm_pref_formset': comm_pref_formset,
            'worker': self.worker,
        })

    def post(self, request, *args, **kwargs):
        comm_pref_formset = self.CommunicationPreferenceFormSet(
            data=request.POST)
        self.set_method_choices(comm_pref_formset)
        success = comm_pref_formset.is_valid()
        if success:
            comm_pref_formset.save()
        return render(request, self.template_name, {
            'form_data': zip(comm_pref_formset, self.descriptions),
            'comm_pref_formset': comm_pref_formset,
            'worker': self.worker,
            'success': success,
        })


class AvailabilitySettingsView(WorkerViewMixin):
    template_name = 'accounts/availability_settings.html'
    form_class = WorkerAvailabilityForm

    def set_context_data(self, request, *args, **kwargs):
        super().set_context_data(request, *args, **kwargs)
        now = timezone.now()
        self.this_week = first_day_of_the_week(now)
        self.next_week = first_day_of_the_week(now + timedelta(days=7))
        this_week_availability = WorkerAvailability.objects.filter(
            worker=self.worker, week=self.this_week).first()
        next_week_availability = WorkerAvailability.objects.filter(
            worker=self.worker, week=self.next_week).first()
        this_week_prefix = 'this_week'
        next_week_prefix = 'next_week'
        self.this_week_form = WorkerAvailabilityForm(
            data=request.POST or None, prefix=this_week_prefix,
            instance=this_week_availability)
        self.next_week_form = WorkerAvailabilityForm(
            data=request.POST or None, prefix=next_week_prefix,
            instance=next_week_availability)

    def _render(self, request, **kwargs):
        kwargs.update({
            'this_week_availability_form': self.this_week_form,
            'next_week_availability_form': self.next_week_form,
            'worker': self.worker,
        })
        return render(request, self.template_name, kwargs)

    def _update_form(self, form, week):
        success = form.is_valid()
        if success:
            # Set private fields we didn't send to the frontend
            form.instance.worker = self.worker
            form.instance.week = week
            form.save()
        return success

    def get(self, request, *args, **kwargs):
        if self.worker.max_autostaff_hours_per_day <= 0:
            raise Http404('Availability settings are not available')

        return self._render(request)

    def post(self, request, *args, **kwargs):
        if self.worker.max_autostaff_hours_per_day <= 0:
            raise Http404('Availability settings are not available')

        this_week_success = self._update_form(
            self.this_week_form, self.this_week)
        next_week_success = self._update_form(
            self.next_week_form, self.next_week)
        success = this_week_success and next_week_success
        success_message = 'Successfully updated availability!'

        return self._render(
            request, success=success, success_message=success_message)

orchestra/templates/accounts/availability_settings.html
{% extends "orchestra/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Availability Settings{% endblock %}

{% block main %}
<div class="main-content login-wrap account-settings container-fluid">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
      {% include "accounts/success.html" %}
      {% include "accounts/settings-tabs.html" with availability_settings="selected" %}
      <div class="card">
        <form action="{% url 'orchestra:availability_settings' %}" method="post">
          {% csrf_token %}
          <div class="container-fluid">
            <div class="row availability-forms">
              <div class="availability-form">
                <div class="availability-form__heading">This week</div>
                <table>
                  {% for field in this_week_availability_form %}
                  <tr>
                    <td>
                      {{ field.errors }}
                      {{ field.label_tag }}
                    </td>
                    <td>{{ field }} hours<td>
                  </tr>
                  {% endfor %}
                </table>
              </div>
              <div class="availability-form">
                <div class="availability-form__heading">Next week</div>
                <table>
                  {% for field in next_week_availability_form %}
                  <tr>
                    <td>
                      {{ field.errors }}
                      {{ field.label_tag }}
                    </td>
                    <td>{{ field }} hours<td>
                  </tr>
                  {% endfor %}
                </table>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                <div class="account-actions">
                  <button type="submit" class="btn btn-primary">Update availability</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

orchestra/templates/accounts/communication_preferences_settings.html
{% extends "orchestra/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Communication Preference Settings{% endblock %}

{% block main %}
<div class="main-content login-wrap account-settings container-fluid">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
      {% include "accounts/success.html" %}
      {% include "accounts/settings-tabs.html" with communication_preference_settings="selected" %}
      <div class="card">
        <form action="{% url 'orchestra:communication_preference_settings' %}" method="post">
          {{ comm_pref_formset.management_form }}
          {% csrf_token %}
          <div class="container-fluid">
            {% for comm_pref_form, description in form_data %}
              {{ comm_pref_form.id }}
              <div class="row spaced">
                <div class="col-lg-12 col-sm-12">
                  <label>
                    {{ description.short_description }}
                  </label>
                  <div> {{ description.long_description }} </div>
                  <div class="communication-methods">
                    {{ comm_pref_form.methods }}
                  </div>

                </div>

              </div>
            {% endfor %}

            <div class="row">
              <div class="col-xs-12">
                <div class="account-actions">
                  <button type="submit" class="btn btn-primary">Update account</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

orchestra/templates/accounts/settings-tabs.html
{% load i18n %}
<div class="account-tabs">
  <a href="{% url 'orchestra:account_settings' %}" class="btn btn-primary {{ account_settings }}">
    {% trans 'Account settings' %}
  </a>
  {% if worker.max_autostaff_hours_per_day > 0 %}
  <a href="{% url 'orchestra:availability_settings' %}" class="btn btn-primary {{ availability_settings }}">
    {% trans 'Work availability' %}
  </a>
  {% endif %}
  <a href="{% url 'orchestra:communication_preference_settings' %}" class="btn btn-primary {{ communication_preference_settings }}">
    {% trans 'Notifications' %}
  </a>
  <a href="{% url 'auth_password_change' %}" class="btn btn-primary {{ password_change }}">
    {% trans 'Change password' %}
  </a>
</div>

orchestra/templates/accounts/settings.html
{% extends "orchestra/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title %}Account Settings{% endblock %}

{% block main %}
<div class="main-content login-wrap account-settings container-fluid">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
      {% include "accounts/success.html" %}
      {% include "accounts/settings-tabs.html" with account_settings="selected" %}
      <div class="card">
        <form action="{% url 'orchestra:account_settings' %}" method="post">
          {% csrf_token %}

            <div class="row">
              <div class="col-xs-12">
                <div class="fieldWrapper">
                  <label for="{{ user_form.first_name.id_for_label }}">First name</label>
                  {{ user_form.first_name|add_class:"form-control" }}
                  <div class="error-field"> {{ user_form.first_name.errors }} </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-12">
                <div class="fieldWrapper">
                  <label for="{{ user_form.last_name.id_for_label }}">Last name</label>
                  {{ user_form.last_name|add_class:"form-control" }}
                  <div class="error-field"> {{ user_form.last_name.errors }} </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-12">
                <div class="fieldWrapper">
                  <label for="{{ worker_form.slack_username.id_for_label }}">Slack username</label>
                  {{ worker_form.slack_username|add_class:"form-control" }}
                  <div class="error-field"> {{ worker_form.slack_username.errors }} </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-12">
                <div class="fieldWrapper">
                  <label for="{{ worker_form.phone.id_for_label }}">Phone</label>
                  <div>
                    {{ worker_form.phone|add_class:"form-control" }}
                  </div>
                  <div class="error-field"> {{ worker_form.phone.errors }} </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-xs-12">
                <div class="account-actions">
                  <button type="submit" class="btn btn-primary">Update account</button>
                </div>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

orchestra/templates/accounts/success.html
{% if success %}
<div class="alert alert-info alert-dismissible" role="alert">
  {{ success_message|default:"Successfully updated preferences!" }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}