orchestra/communication/urls.py
from django.urls import re_path

from orchestra.communication.views import accept_staffing_request_inquiry
from orchestra.communication.views import available_staffing_requests
from orchestra.communication.views import reject_staffing_request_inquiry

app_name = 'communication'

urlpatterns = [
    # Interface API
    re_path(r'^accept_staffing_request_inquiry/(?P<staffing_request_inquiry_id>[0-9]+)/$',  # noqa
            accept_staffing_request_inquiry,
            name='accept_staffing_request_inquiry'),
    re_path(r'^reject_staffing_request_inquiry/(?P<staffing_request_inquiry_id>[0-9]+)/$',  # noqa
            reject_staffing_request_inquiry,
            name='reject_staffing_request_inquiry'),
    re_path(r'^available_staffing_requests/',
            available_staffing_requests,
            name='available_staffing_requests'),
]

orchestra/urls.py
from django.conf.urls import include
from django.urls import re_path

from orchestra.views import index
from orchestra.views import newindex
from orchestra.views import status

app_name = 'orchestra'

urlpatterns = [
    re_path(r'^api/',
            include('orchestra.api_urls', namespace='orchestra')),
    re_path(r'^communication/',
            include('orchestra.communication.urls',
                    namespace='communication')),
    re_path(r'^newapp/?', newindex, name='newindex'),
    re_path(r'^app/?', index, name='index'),
    re_path(r'', include('orchestra.accounts.urls')),
    re_path(r'^bots/', include('orchestra.bots.urls', namespace='bots')),
    re_path(r'^todos/', include('orchestra.todos.urls', namespace='todos')),

    # Health check status
    re_path(r'^status/', status, name='status'),
]

orchestra/models/communication/models.py
from bitfield import BitField
from django.db import models

from orchestra.models.communication.managers import \
    CommunicationPreferenceManager
from orchestra.models.communication.mixins import CommunicationPreferenceMixin
from orchestra.models.communication.mixins import StaffBotRequestMixin
from orchestra.models.communication.mixins import StaffingRequestInquiryMixin
from orchestra.models.communication.mixins import StaffingResponseMixin
from orchestra.models.core.models import Task
from orchestra.models.core.models import Worker
from orchestra.utils.models import BaseModel
from orchestra.utils.models import ChoicesEnum


class CommunicationPreference(CommunicationPreferenceMixin, BaseModel):
    """
        A CommunicationPreference object defines how a Worker would like to
        contacted for a given CommunicationType.

        Attributes:
            worker (orchestra.models.Worker):
                Django user that the preference represents.
            methods (BitField):
                The ways in which the user would like to be contacted.
            type (CommunicationType):
                The type of communication to which this preference applies.
    """
    objects = CommunicationPreferenceManager()

    class CommunicationMethods:
        SLACK = 'slack'
        EMAIL = 'email'

    COMMUNICATION_METHODS = (
        (CommunicationMethods.SLACK, 'Slack'),
        (CommunicationMethods.EMAIL, 'Email'),
    )

    class CommunicationType(ChoicesEnum):
        TASK_STATUS_CHANGE = 'task_status_change'
        NEW_TASK_AVAILABLE = 'new_task_available'

    COMMUNICATION_TYPE_DESCRIPTIONS = {
        CommunicationType.TASK_STATUS_CHANGE:
        {
            'short_description': 'Task Status Changes',
            'long_description':
            """
            When a task status changes (e.g., when it moves from in
            review to returned from reviewer), you will automatically
            receive a notification in the project Slack group. Select
            whether you would like to receive an email notification as
            well.
            """
        },
        CommunicationType.NEW_TASK_AVAILABLE:
        {
            'short_description': 'New Tasks',
            'long_description':
            """
            Select your preferred channel for being notified when a
            new task is available to work on.
            """
        }
    }

    worker = models.ForeignKey(Worker, on_delete=models.CASCADE)
    methods = BitField(flags=COMMUNICATION_METHODS,
                       blank=True, null=True, default=None)
    communication_type = models.IntegerField(
        choices=CommunicationType.choices())

    class Meta:
        app_label = 'orchestra'
        unique_together = (('worker', 'communication_type'),)


class StaffBotRequest(StaffBotRequestMixin, BaseModel):
    """
    A StaffBotRequest object defines a new task that needs
    a worker for a specific role.

    Attributes:
        task (orchestra.models.Task):
            The task that needs a worker assignment
        required_role_counter (int):
            Counter that tells which expert is a new worker
            going to be on a task
        request_cause (RequestCause):
            The cause for request
        project_description (str):
            Description of the project
        status (Status)
            Status of the request
        last_inquiry_sent (DateTimeField):
            The datetime the most recent inquiry was sent.
    """
    class RequestCause(ChoicesEnum):
        USER = 'user'
        TASK_POLICY = 'task policy'
        RESTAFF = 'restaff'

    class Status(ChoicesEnum):
        SENDING_INQUIRIES = 'sending inquiries'
        DONE_SENDING_INQUIRIES = 'done sending inquiries'
        CLOSED = 'closed'

    task = models.ForeignKey(
        Task, related_name='staffing_requests', on_delete=models.CASCADE)
    required_role_counter = models.IntegerField()
    request_cause = models.IntegerField(choices=RequestCause.choices())
    project_description = models.TextField(null=True, blank=True)
    status = models.IntegerField(
        default=Status.SENDING_INQUIRIES.value,
        choices=Status.choices())
    last_inquiry_sent = models.DateTimeField(null=True)


class StaffingRequestInquiry(StaffingRequestInquiryMixin, BaseModel):
    """
    A StaffingRequestInquiry object defines how a Worker was contacted to
    work on a StaffBotRequest

    Attributes:
        communication_preference (orchestra.models.CommunicationPreference):
            Django user that the request is sent to
        request (orchestra.models.StaffBotRequest):
            Request object associated with inquiry
        communication_method (CommunicationMethod):
            Method by which a worker is going to be contacted. If a worker has
            specified availability for automatic task assignment, we create an
            inquiry with a communication method of 'already opted in', since we
            don't actually need to reach out to the worker.
    """

    class CommunicationMethod(ChoicesEnum):
        SLACK = 'slack'
        EMAIL = 'email'
        PREVIOUSLY_OPTED_IN = 'already opted in'

    request = models.ForeignKey(StaffBotRequest,
                                on_delete=models.CASCADE,
                                null=True,
                                related_name='inquiries')
    communication_preference = models.ForeignKey(
        CommunicationPreference, on_delete=models.CASCADE)
    communication_method = models.IntegerField(
        choices=CommunicationMethod.choices())


class StaffingResponse(StaffingResponseMixin, BaseModel):
    """
    A StaffingResponse object stores a response from a worker and
    whether the worker got the task.

    Attributes:
        request_inquiry (orchestra.models.StaffingRequestInquiry):
            Request inquiry associated with a response
        response_text (str):
            Response text that a Worker provided
        is_available (bool):
            True if a Worker is ready to work on the Task
        is_winner (bool):
            True if a Worker was selected to work on the Task
    """
    request_inquiry = models.ForeignKey(StaffingRequestInquiry,
                                        on_delete=models.CASCADE,
                                        related_name='responses')
    response_text = models.TextField(blank=True, null=True)
    is_available = models.BooleanField()
    is_winner = models.BooleanField(null=True)

orchestra/communication/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import render

from orchestra.bots.errors import StaffingResponseException
from orchestra.communication.staffing import get_available_requests
from orchestra.communication.staffing import handle_staffing_response
from orchestra.models import Worker


@login_required
def accept_staffing_request_inquiry(request,
                                    staffing_request_inquiry_id):
    worker = Worker.objects.get(user=request.user)
    response = handle_staffing_response(
        worker, staffing_request_inquiry_id, is_available=True)

    if response is None:
        raise Http404
    return render(request, 'communication/staffing_request_accepted.html',
                  {
                      'response': response,
                  })


@login_required
def reject_staffing_request_inquiry(request,
                                    staffing_request_inquiry_id):
    worker = Worker.objects.get(user=request.user)
    try:
        response = handle_staffing_response(
            worker, staffing_request_inquiry_id, is_available=False)
    except StaffingResponseException:
        return render(request,
                      'communication/staffing_response_not_permitted.html',
                      {})
    if response is None:
        raise Http404

    next_path = request.GET.get('next')
    if next_path:
        return HttpResponseRedirect(next_path)
    else:
        return render(request, 'communication/staffing_request_rejected.html',
                      {})


@login_required
def available_staffing_requests(request):
    worker = Worker.objects.get(user=request.user)
    return render(request, 'communication/available_staffing_requests.html',
                  {
                      'requests': get_available_requests(worker),
                  })

orchestra/templates/communication/available_staffing_requests.html
{% extends 'orchestra/base.html' %}
{% load static %}

{% block title %} Available Tasks {% endblock %}

{% block header %}
<meta http-equiv="refresh" content="600" />
{% endblock %}

{% block main %}
<div class="container-fluid main-content staffing-container">
  <div class="col-lg-12">
    <div class="card">
      {% if requests|length > 0 %}
      <table class="table">
        <tr>
          <th class="row-project">Project</th>
          <th class="row-project-description tags-col">Project description</th>
          <th class="row-task">Task</th>
          <th class="row-details">Details</th>
          <th class="row-created-at">Available since</th>
          <th class="row-actions">Actions</th>
        </tr>
        {% for request in requests %}
        <tr>
          <td>{{ request.workflow_description }}</td>
          <td class="tags-col">
            {{ request.project_description }}
            <br>
            {% for tag in request.tags %}
              <span class="label label-{{tag.status}}">
                {{tag.label}}
              </span>
            {% endfor %}
          </td>
          <td>{% if request.role_counter > 0 %}[Review] {% endif %}{{ request.step_description }}</td>
          <td>{{ request.detailed_description | safe }}</td>
          <td>{{ request.available_datetime|date:"m/d/Y H:i" }}</td>
          <td>
            <a href="{{ request.accept_url }}" class="btn btn-primary btn-sm" role="button">Accept</a>
            <a href="{{ request.reject_url }}" class="btn btn-primary btn-sm" role="button">Ignore</a>
          </td>
        </tr>
        {% endfor %}
      </table>
      {% else %}
      <h2>There are no tasks available at the moment.</h2>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

orchestra/templates/communication/staffing_request_accepted.html
{% extends 'orchestra/base.html' %}
{% load static %}

{% block title %}
  {% if response.is_winner %}
    Success!
  {% else %}
    Task Taken
  {% endif %}
{% endblock %}

{% block main %}
<div class="container-fluid main-content communication-container">
  <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
    <div class="card">
        {% if response.is_winner %}
        <h2>
          Congratulations! You got the task :)
        </h2>
          <div class="row spaced">
            <a href="{% url "orchestra:index" %}/task/{{ response.request_inquiry.request.task.id }}/" class="btn btn-primary btn-lg">
              View Task
            </a>
          </div>
        {% else %}
          <h2>
            Unfortunately, task has already been taken :(
          </h2>
          <div class="row spaced">
            <a href="{% url "orchestra:communication:available_staffing_requests" %}" class="btn btn-primary btn-lg">
              View All Available Tasks
            </a>
          </div>
        {% endif %}
    </div>
  </div>
</div>
{% endblock %}

orchestra/templates/communication/staffing_request_rejected.html
{% extends 'orchestra/base.html' %}
{% load static %}

{% block title %}Thank you{% endblock %}

{% block main %}
<div class="container-fluid main-content communication-container">
  <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
    <div class="card">
        <h2>
          Thanks for responding!
        </h2>
    </div>
  </div>
</div>
{% endblock %}

orchestra/templates/communication/staffing_response_not_permitted.html
{% extends 'orchestra/base.html' %}
{% load static %}

{% block title %}
Task cannot be rejected.
{% endblock %}

{% block main %}
<div class="container-fluid main-content communication-container">
  <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">
    <div class="card">
      Unfortunately, you can not reject the task after accepting it. Reach out if you can no longer work on this task!
    </div>
  </div>
</div>
{% endblock %}